{% set name = "atomicrex" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3515b409a743216230f10685948867c9261fc247c2f6cc868865dd3722842ef7
  patches:
    - conda.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - cmake
    - vim  # required for xxd 
  host:
    - python
    - boost-cpp
    - libxml2
    - muparser
    - nlopt
    - pybind11
  run:
    - python
    - boost-cpp
    - libxml2
    - muparser
    - nlopt

test:
  imports:
    - atomicrex

about:
  home: https://www.atomicrex.org
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: A tool for the construction of interaction models

  description: |
    atomicrex is a versatile tool for the construction of advanced 
    atomistic models. It is written in C++ and python. It was primarily 
    developed to fit interatomic potential models. Thanks to its 
    flexible generic structure its application range, however, is much 
    larger. 
  doc_url: https://www.atomicrex.org
  dev_url: https://gitlab.com/atomicrex/atomicrex

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
