{% set name = "atomicrex" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 2b0a074e20cfb4bbb31a2d2e70707fee6874592a5cdf15af0cec9866f97c4101
  patches:
    - conda.patch

build:
  number: 4
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
    - cmake
    - vim  # required for xxd 
  host:
    - python
    - libboost-devel
    - libxml2
    - muparser
    - nlopt
    - pybind11
  run:
    - python
    - libxml2
    - muparser
    - nlopt

test:
  imports:
    - atomicrex

about:
  home: https://www.atomicrex.org
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: A tool for the construction of interaction models

  description: |
    atomicrex is a versatile tool for the construction of advanced 
    atomistic models. It is written in C++ and python. It was primarily 
    developed to fit interatomic potential models. Thanks to its 
    flexible generic structure its application range, however, is much 
    larger. 
  doc_url: https://www.atomicrex.org
  dev_url: https://gitlab.com/atomicrex/atomicrex

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
    - srmnitc
